name: PR Title Validation

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  validate-pr-title:
    runs-on: windows
    steps:
      - name: Validate PR title format
        run: |
          # Gitea API token (set it as a secret in Gitea)
          $GITEA_API_TOKEN="${{ secrets.PAT }}"

          # Repository and PR details
          $REPO_OWNER="${{ github.repository_owner }}"
          $REPO_NAME="${{ github.event.repository.name }}"
          $PR_NUMBER="${{ github.event.pull_request.number }}"

          # Fetch the PR title using Gitea API
          $PR_RESPONSE = Invoke-RestMethod -Uri "https://git.websurfingstudios.com/api/v1/repos/$REPO_OWNER/$REPO_NAME/pulls/$PR_NUMBER" `
            -Headers @{ "Authorization" = "token $GITEA_API_TOKEN" }

          # Parse the PR title from the response
          $PR_TITLE = $PR_RESPONSE.title

          # Check if the PR title matches the format "AB#<number> - <title>"
          if ($PR_TITLE -match "^AB#[0-9]+ - .+" -or $PR_TITLE -match "^AB#\.{3} - .+") {
            Write-Host "PR title is valid: $PR_TITLE"
          } else {
            Write-Host "Error: PR title must be in the format 'AB#<number> - <title>'"
            exit 1
          }